version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    tty: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistent volume for RabbitMQ data
    environment:
      RABBITMQ_DEFAULT_USER: "root" # Set default RabbitMQ user
      RABBITMQ_DEFAULT_PASS: "1234" # Set default RabbitMQ password
    ports:
      - "15672:15672"
      - "5672:5672"

  # go-server:
  #   build: .
  #   container_name: go-server
  #   environment:
  #     SERVER_HOST: 0.0.0.0
  #     SERVER_PORT: 8080
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: root
  #     DB_PASS: 1234
  #     DB_NAME: shop
  #     DB_SSL_MODE: disable
  #     DB_TIMEZONE: Asia/Bangkok
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:
